# Generated by Django 2.0.7 on 2018-08-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
