# Generated by Django 2.0.7 on 2018-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
